name: Convert Clash Subscription to V2Ray

on:
  schedule:
    - cron: '0 19 * * *'   
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: |
        go get -u github.com/Dreamacro/clash
      env:
        GO111MODULE: on

    - name: Convert Clash to V2Ray
      run: |
        cd Surfboard
        go-clash -p https://github.com/Smurf-Yvan/Proxy/raw/main/Surfboard/V2ray.yaml -f v2ray.txt
      env:
        GO111MODULE: on

    - name: Commit and push converted config
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add v2ray-config.json
        git commit -m "Convert Clash to V2Ray config"
        git push
