name: Manage Azure VM

on:
  workflow_dispatch:

jobs:
  manage-vm:
    runs-on: windows-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
