name: Manage Azure VM

on:
  workflow_dispatch:

jobs:
  manage-vm:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/actions/login@V1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az webapp list --query "[?state=='Running']"
