name: Manage Azure VM

on:
  schedule:
    - cron: '0 18 * * *'   
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Stop Azure VM
        run: |
          az vm deallocate --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} --name ${{ secrets.AZURE_VM_NAME }}
          sleep 3

      - name: Start Azure VM
        run: |
          az vm start --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} --name ${{ secrets.AZURE_VM_NAME }}

      - name: Get VM Public IP
        id: get-ip
        run: |
          ip=$(az vm show -d -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} -n ${{ secrets.AZURE_VM_NAME }} --query publicIps -o tsv)
          echo "::set-output name=ip::$ip"

      - name: Update Personal.conf file
        run: |
          cd Surfboard
          sed -i "14s/.*/VPN = vmess, $(echo ${{ steps.get-ip.outputs.ip }}), 610, username=0497410d-4cac-4cdb-b2ba-14f89625c320, tls=false, vmess-aead=true, skip-cert-verify=true, tfo=false, udp-relay=true/" Personal.conf

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update files from GitHub Action"
          git push -f origin main

      - name: Send IP Address via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Azure VM IP Address'
          to: ${{ secrets.RECIPIENT_EMAILS }}
          from: ${{ secrets.EMAIL_USERNAME }}
          message: 'VPN的IP地址更新为: ${{ steps.get-ip.outputs.ip }}'
        continue-on-error: true
