name: Manage Azure VM

on:
  workflow_dispatch:

jobs:
  manage-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          creds_source: ServicePrincipal
          subscription_id: c7c3028b-069d-4b91-858c-09173b3d3669

      - name: List Azure resource groups
        id: list-resource-groups
        run: |
          az group list --query [].name -o table

