name: Clash VPN

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      Date:
        description: '日期 格式YYYY/MM/YYYYMMDD'
        required: false
jobs:
  Update-VPN:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set dynamic date format
        run: |
          DATE=$(date +'%Y/%m/%Y%m%d')
          echo "DATE=${DATE}" >> $GITHUB_ENV
      - name: Run Update VPN
        run: |
          cd Clash
          if [ -n "${{ github.event.inputs.Date }}" ]; then
            wget https://nodefree.org/dy/${{ github.event.inputs.Date }}.yaml -O VPN.yaml
          else
            wget https://nodefree.org/dy/$DATE.yaml -O VPN.yaml
          fi
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update files from GitHub Action"
          git push -f origin main
