name: Clash VPN

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      Date:
        description: '日期 格式YYYY/MM/YYYYMMDD'
        required: false
jobs:
  Update-VPN:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set dynamic date format
        run: |
          DATE=$(date +'%Y/%m/%Y%m%d')
          echo "DATE=${DATE}" >> $GITHUB_ENV
      - name: Run Update VPN
        run: |
          if [ -n "${{ github.event.inputs.Date }}" ]; then
            wget https://nodefree.org/dy/${{ github.event.inputs.Date }}.yaml -O VPN.yaml
          else
            wget https://nodefree.org/dy/$DATE.yaml -O VPN.yaml
          fi
          rm -rf /Clash/VPN.yaml
          mv VPN.yaml Clash/
      - name: Commit and Push Changes
        run: |
          git push -f origin main
