name: Manage Azure VM

on:
  workflow_dispatch:

jobs:
  manage-azure-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
      
      - name: Log in to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Stop Azure VM
        run: az vm deallocate --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_VM_NAME }} --no-wait
        
      - name: Wait for VM to deallocate
        run: sleep 60s  # Adjust this time according to your VM's deallocation time
        
      - name: Start Azure VM
        run: az vm start --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_VM_NAME }}
        
      - name: Wait for VM to start
        run: sleep 60s  # Adjust this time according to your VM's startup time
        
      - name: Get VM Public IP
        id: get-vm-ip
        run: |
          ip=$(az vm show -d -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_VM_NAME }} --query publicIps -o tsv)
          echo "::set-output name=ip::$ip"
        
      - name: Write IP to file
        run: echo "${{ steps.get-vm-ip.outputs.ip }}" > ${{ secrets.OUTPUT_FILE_PATH }}
