name: Manage Azure VM

on:
  workflow_dispatch:

jobs:
  manage-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        continue-on-error: true

      - name: Stop Azure VM
        run: |
          az vm deallocate --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name ${{ secrets.VM_NAME }}
        continue-on-error: true

      - name: Start Azure VM
        run: |
          az vm start --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name ${{ secrets.VM_NAME }}
        continue-on-error: true

      - name: Get VM IP Address
        id: get-vm-ip
        run: |
          vm_ip=$(az vm show -d --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name ${{ secrets.VM_NAME }} --query publicIps -o tsv)
          echo "::set-output name=ip_address::${vm_ip}"
        continue-on-error: true

      - name: Write IP Address to File
        run: echo "${{ steps.get-vm-ip.outputs.ip_address }}" > vm_ip.txt

      - name: Commit IP Address to Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add vm_ip.txt
          git commit -m "Update VM IP Address"
          git push
        continue-on-error: true
